### Richiesta GET per ottenere la lista degli autori
GET http://localhost:5050/authors

### Richiesta GET per ottenere un singolo autore per ID
GET http://localhost:5050/authors/1

### Richiest GET per ottenere i BlogPost
GET http://localhost:5050/blogposts