### Richiesta GET per ottenere la lista degli users
GET http://localhost:5050/users



### Richiest GET per ottenere i BlogPost
GET http://localhost:5050/blogposts

### Richiesta Get per Singolo Blogpost ID

GET http://localhost:5050/blogposts/65201821655e04b71200a01e/comments

### Richiesta Get per titolo

GET http://localhost:5050/blogposts?title=artificiale

### Richiest Get per id specifico del post del nome autore

GET http://localhost:5050/blogposts/65201821655e04b71200a01/John_Doe

###

POST http://localhost:5050/users/create HTTP/1.1
Content-Type: application/json

{
    "firstname": "Michele",
    "lastname": "Lo Presti",
    "email": "mikeyoulend@gmail.com",
    "password": "d735pa"
}

###


POST   http://localhost:5050/login HTTP/1.1
Content-Type: application/json

{
    "email": "mikeyoulend@gmail.com",
    "password": "d735pa"
}



